// Generated by CoffeeScript 1.6.2
(function() {
  var evaluate_array, job, needle, set;

  set = [18897109, 12828837, 9461105, 6371773, 5965343, 5946800, 5582170, 5564635, 5268860, 4552402, 4335391, 4296250, 4224851, 4192887, 3439809, 3279833, 3095313, 2812896, 2783243, 2710489, 2543482, 2356285, 2226009, 2149127, 2142508, 2134411];

  needle = 100000000;

  evaluate_array = function(s, sum) {
    var a, arr, i, _i, _j, _k, _l, _len, _results;

    arr = (function() {
      _results = [];
      for (var _i = 0; 0 <= sum ? _i <= sum : _i >= sum; 0 <= sum ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
    for (i = _j = 1; _j <= sum; i = _j += 1) {
      arr[i] = -1;
    }
    console.log("created work array");
    for (_k = 0, _len = s.length; _k < _len; _k++) {
      a = s[_k];
      for (i = _l = 0; _l <= sum; i = _l += 1) {
        if (arr[i] !== -1 && arr[i] !== a && (k + a) < sum) {
          if (arr[k + a] === -1) {
            arr[k + a] = a;
          }
        }
      }
    }
    return arr;
  };

  console.log("start eval");

  job = evaluate_array(set, needle);

  console.log(job[needle]);

}).call(this);
